#hikari DBCP with h2 DB
spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:testDB
      username: sa
      password:
      maximum-pool-size: 12
      minimum-idle: 5
      auto-commit: true
      connection-timeout: 300000
      max-lifetime: 1200000
      idle-timeout: 300000
  h2:
    console:
      enabled: true
      path: /h2-console

  flyway:
    baseline-on-migrate: true
    url: jdbc:h2:mem:testDB
    user: sa
    password:
    encoding: UTF-8
    enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        default_batch_fetch_size: 1000
    show-sql: true
    generate-ddl: false

graphql:
  spqr:
    gui:
      enabled: true